// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:b2b_freshmore/base_architecture/domain/entity/currency_entity.dart';
import 'package:b2b_freshmore/base_architecture/domain/entity/user_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CurrencyEntityAdapter());
    registerAdapter(DataEntityAdapter());
    registerAdapter(UserEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CurrencyEntityAdapter());
    registerAdapter(DataEntityAdapter());
    registerAdapter(UserEntityAdapter());
  }
}
